const KEYS = { coupons: 'mbm-admin-coupons', settings: 'mbm-admin-settings', auth: 'mbm-admin-auth-v2', session: 'mbm-admin-session-v2', loginAttempts: 'mbm-admin-login-attempts' };
const moneyAdmin = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const get = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch (_) { return fallback; } };
const put = (key, value) => localStorage.setItem(key, JSON.stringify(value));
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
let catalog = getStoreProducts();
let coupons = get(KEYS.coupons, []);
let settings = get(KEYS.settings, { storeName: 'CHUTEIRAS MBM', whatsapp: '5531983058097', message: 'Olá! Quero saber mais sobre uma chuteira.' });
let pendingImage = '';

async function hash(text) { const bytes = new TextEncoder().encode(text); const digest = await crypto.subtle.digest('SHA-256', bytes); return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, '0')).join(''); }
function notice(text) { const toast = $('#toast'); toast.textContent = text; toast.classList.add('show'); clearTimeout(window.mbmToast); window.mbmToast = setTimeout(() => toast.classList.remove('show'), 2600); }
function save() { saveStoreProducts(catalog); put(KEYS.coupons, coupons); put(KEYS.settings, settings); }
function session() { return get(KEYS.session, null); }
function hasSession() { const current = session(); return current && current.expiresAt > Date.now(); }
function openApp() { $('#admin-login').hidden = true; $('#admin-app').hidden = false; $('#admin-user-name').textContent = session()?.email || 'Administradora'; render(); }
function availability(product) { return product.active === false ? 'Esgotado' : 'Disponível'; }
function showLogin(message = '') { $('#setup-view').hidden = true; $('#login-view').hidden = false; $('#login-feedback').textContent = message; }
function showSetup(message = '') { $('#login-view').hidden = true; $('#setup-view').hidden = false; $('#setup-feedback').textContent = message || 'Use pelo menos 8 caracteres.'; }
function updatePreview(src = '') { pendingImage = src; $('#image-preview').hidden = !src; $('#image-preview-img').src = src || ''; }

function renderProducts() { const term = $('#admin-product-search').value.trim().toLowerCase(); const list = catalog.filter(product => `${product.name} ${product.brand}`.toLowerCase().includes(term)); $('#admin-product-count').textContent = `${list.length} produtos`; $('#admin-products-table').innerHTML = list.map(product => `<tr><td><div class="table-product"><img src="${escapeHtml(product.image)}" alt=""><strong>${escapeHtml(product.name)}</strong></div></td><td>${escapeHtml(product.brand)}</td><td>${escapeHtml(product.category)}</td><td>${moneyAdmin.format(product.price)}</td><td><span class="status ${product.active === false ? 'inactive' : 'active-status'}">${availability(product)}</span></td><td><div class="table-actions"><button class="icon-button" data-edit="${product.id}">Editar</button><button class="icon-button" data-toggle="${product.id}">${product.active === false ? 'Ativar' : 'Esgotar'}</button><button class="icon-button danger" data-delete="${product.id}">Remover</button></div></td></tr>`).join('') || '<tr><td colspan="6" class="empty">Nenhum produto encontrado.</td></tr>'; }
function renderCoupons() { $('#coupons-grid').innerHTML = coupons.map((coupon, index) => `<article class="coupon-card"><p>${coupon.active ? 'ATIVO' : 'PAUSADO'}</p><h3>${escapeHtml(coupon.code)}</h3><strong>${coupon.discount}% OFF</strong><span>Válido até ${new Date(coupon.validity + 'T12:00:00').toLocaleDateString('pt-BR')}</span><button data-coupon="${index}">${coupon.active ? 'Pausar' : 'Ativar'}</button></article>`).join('') || '<p class="empty">Nenhum cupom cadastrado.</p>'; }
function render() { renderProducts(); renderCoupons(); }
function switchView(view) { $$('.admin-nav button').forEach(button => button.classList.toggle('active', button.dataset.view === view)); $$('.admin-view').forEach(section => section.classList.toggle('active', section.id === `view-${view}`)); $('#admin-title').textContent = { products: 'Produtos', coupons: 'Cupons', settings: 'Configurações' }[view]; window.scrollTo({ top: 0, behavior: 'smooth' }); }
function openProduct(id) { const product = catalog.find(item => item.id === id); $('#product-form-wrap').hidden = false; $('#product-form').reset(); updatePreview(product?.image || ''); if (product) { $('#product-id').value = product.id; $('#product-name').value = product.name; $('#product-brand').value = product.brand; $('#product-category').value = product.category; $('#product-price').value = product.price; $('#product-description').value = product.description || ''; } $('#product-name').focus(); }
function closeProduct() { $('#product-form-wrap').hidden = true; updatePreview(''); }
function syncCatalog() { catalog = getStoreProducts(); render(); }
function readImage(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = reject; reader.onload = () => { const image = new Image(); image.onerror = reject; image.onload = () => { const max = 1400; const scale = Math.min(1, max / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL('image/jpeg', .8)); }; image.src = reader.result; }; reader.readAsDataURL(file); }); }

$('#show-setup').onclick = () => showSetup(); $('#show-login').onclick = () => showLogin();
$('#setup-form').onsubmit = async event => { event.preventDefault(); const email = $('#setup-email').value.trim().toLowerCase(); const password = $('#setup-password').value; if (password.length < 8 || password !== $('#setup-password-confirm').value) return showSetup('As senhas precisam ser iguais e ter pelo menos 8 caracteres.'); put(KEYS.auth, { email, passwordHash: await hash(password), createdAt: Date.now() }); $('#setup-form').reset(); showLogin('Acesso criado. Entre com sua nova senha.'); };
$('#login-form').onsubmit = async event => { event.preventDefault(); const auth = get(KEYS.auth, null); if (!auth) return showSetup('Crie primeiro o acesso administrativo.'); const attempts = get(KEYS.loginAttempts, { count: 0, lockedUntil: 0 }); if (attempts.lockedUntil > Date.now()) return $('#login-feedback').textContent = 'Acesso temporariamente bloqueado. Tente novamente em alguns minutos.'; const valid = $('#admin-email').value.trim().toLowerCase() === auth.email && await hash($('#admin-password').value) === auth.passwordHash; if (!valid) { const count = attempts.count + 1; put(KEYS.loginAttempts, { count, lockedUntil: count >= 5 ? Date.now() + 10 * 60 * 1000 : 0 }); return $('#login-feedback').textContent = count >= 5 ? 'Acesso bloqueado por 10 minutos.' : 'E-mail ou senha incorretos.'; } put(KEYS.loginAttempts, { count: 0, lockedUntil: 0 }); put(KEYS.session, { email: auth.email, expiresAt: Date.now() + 8 * 60 * 60 * 1000 }); openApp(); notice('Painel desbloqueado.'); };
$('#logout').onclick = () => { localStorage.removeItem(KEYS.session); location.reload(); };
$$('.admin-nav button').forEach(button => button.onclick = () => switchView(button.dataset.view));
$('#open-product-form').onclick = () => openProduct(); $('#cancel-product').onclick = closeProduct; $('#admin-product-search').oninput = renderProducts;
$('#product-image-file').onchange = async event => { const file = event.target.files[0]; if (!file) return; if (file.size > 12 * 1024 * 1024) return notice('Escolha uma imagem de até 12 MB.'); try { updatePreview(await readImage(file)); notice('Imagem pronta para salvar.'); } catch (_) { notice('Não foi possível ler esta imagem.'); } };
$('#remove-image').onclick = () => { $('#product-image-file').value = ''; updatePreview(''); };
$('#product-form').onsubmit = event => { event.preventDefault(); const id = Number($('#product-id').value); const old = catalog.find(product => product.id === id); const image = pendingImage || old?.image; if (!image) return notice('Escolha uma imagem para o produto.'); const item = { id: id || Date.now(), name: $('#product-name').value.trim(), brand: $('#product-brand').value, category: $('#product-category').value, price: Number($('#product-price').value), image, description: $('#product-description').value.trim() || 'Produto original. Consulte tamanhos disponíveis pelo WhatsApp.', sizes: [], stock: 1, active: old?.active ?? true }; catalog = id ? catalog.map(product => product.id === id ? item : product) : [item, ...catalog]; try { save(); closeProduct(); render(); notice('Produto salvo e vitrine atualizada.'); } catch (_) { notice('A imagem ficou grande demais. Escolha uma foto menor.'); } };
$('#admin-products-table').onclick = event => { const id = Number(event.target.dataset.edit || event.target.dataset.toggle || event.target.dataset.delete); if (!id) return; if (event.target.dataset.edit) return openProduct(id); if (event.target.dataset.toggle) { catalog = catalog.map(product => product.id === id ? { ...product, active: product.active === false } : product); save(); render(); return notice('Status atualizado na vitrine.'); } if (event.target.dataset.delete && window.confirm('Remover este produto da vitrine?')) { catalog = catalog.filter(product => product.id !== id); save(); render(); notice('Produto removido.'); } };
$('#open-coupon-form').onclick = () => $('#coupon-form-wrap').hidden = false;
$('#coupon-form').onsubmit = event => { event.preventDefault(); const code = $('#coupon-code').value.trim().toUpperCase(); if (coupons.some(coupon => coupon.code === code)) return notice('Este cupom já existe.'); coupons.unshift({ code, discount: Number($('#coupon-discount').value), validity: $('#coupon-validity').value, active: true }); save(); $('#coupon-form-wrap').hidden = true; event.target.reset(); renderCoupons(); notice('Cupom criado.'); };
$('#coupons-grid').onclick = event => { const index = Number(event.target.dataset.coupon); if (Number.isInteger(index)) { coupons[index].active = !coupons[index].active; save(); renderCoupons(); notice('Cupom atualizado.'); } };
$('#settings-form').onsubmit = event => { event.preventDefault(); settings = { storeName: $('#setting-store-name').value.trim(), whatsapp: $('#setting-whatsapp').value.replace(/\D/g, ''), message: $('#setting-message').value.trim() }; save(); notice('Configurações salvas.'); };
$('#password-form').onsubmit = async event => { event.preventDefault(); const auth = get(KEYS.auth, null); if (!auth || await hash($('#current-password').value) !== auth.passwordHash) return notice('Senha atual incorreta.'); const next = $('#new-password').value; if (next.length < 8 || next !== $('#new-password-confirm').value) return notice('A nova senha precisa coincidir e ter 8 caracteres.'); put(KEYS.auth, { ...auth, passwordHash: await hash(next) }); event.target.reset(); notice('Senha atualizada com segurança.'); };
window.addEventListener('storage', event => { if (event.key === MBM_CATALOG_KEY) syncCatalog(); });
if (!get(KEYS.auth, null)) showSetup('Crie o primeiro acesso administrativo.'); else if (hasSession()) openApp(); else showLogin();
$('#setting-store-name').value = settings.storeName; $('#setting-whatsapp').value = settings.whatsapp; $('#setting-message').value = settings.message;
