const WHATSAPP_NUMBER = '5500000000000'; // Troque pelo número da loja: 55 + DDD + número
const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
let cart = JSON.parse(localStorage.getItem('mbm-cart') || '[]');
const grid = document.querySelector('#product-grid');
const search = document.querySelector('#search'), brandFilter = document.querySelector('#brand-filter'), categoryFilter = document.querySelector('#category-filter'), sort = document.querySelector('#sort');
const brands = [...new Set(products.map(p=>p.brand))];
brandFilter.innerHTML += brands.map(brand=>`<option>${brand}</option>`).join('');
function filteredProducts(){let result=products.filter(p=>(brandFilter.value==='Todas'||p.brand===brandFilter.value)&&(categoryFilter.value==='Todas'||p.category===categoryFilter.value)&&`${p.name} ${p.brand}`.toLowerCase().includes(search.value.toLowerCase()));return result.sort((a,b)=>sort.value==='low'?a.price-b.price:sort.value==='high'?b.price-a.price:a.id-b.id)}
function renderProducts(){const list=filteredProducts();document.querySelector('#result-count').textContent=`${list.length} ${list.length===1?'modelo encontrado':'modelos encontrados'}`;grid.innerHTML=list.map(p=>`<article class="product-card"><button class="image-button" data-product="${p.id}" aria-label="Ver ${p.name}"><img src="${p.image}" alt="Imagem demonstrativa de chuteira"></button><div class="product-info"><p class="tag">${p.brand} · ${p.category}</p><h3>${p.name}</h3><p class="price">${money.format(p.price)}</p><button class="button add" data-add="${p.id}">Adicionar <span>+</span></button></div></article>`).join('') || '<p class="empty">Nenhum modelo encontrado.</p>'}
function renderCart(){document.querySelector('#cart-count').textContent=cart.reduce((n,i)=>n+i.quantity,0);const items=document.querySelector('#cart-items');if(!cart.length){items.innerHTML='<p class="empty">Seu carrinho está vazio.</p>'}else{items.innerHTML=cart.map(item=>{const p=products.find(p=>p.id===item.id);return `<article class="cart-item"><img src="${p.image}" alt=""><div><h3>${p.name}</h3><p>${money.format(p.price)}</p><div class="quantity"><button data-quantity="${p.id}" data-step="-1">−</button><span>${item.quantity}</span><button data-quantity="${p.id}" data-step="1">+</button><button class="remove" data-remove="${p.id}">Remover</button></div></div></article>`}).join('')}document.querySelector('#cart-total').textContent=money.format(cart.reduce((sum,item)=>sum+products.find(p=>p.id===item.id).price*item.quantity,0));localStorage.setItem('mbm-cart',JSON.stringify(cart))}
function addToCart(id){const entry=cart.find(i=>i.id===id);entry?entry.quantity++:cart.push({id,quantity:1});renderCart()}
function changeQuantity(id,step){const entry=cart.find(i=>i.id===id);entry.quantity+=step;if(entry.quantity<=0)cart=cart.filter(i=>i.id!==id);renderCart()}
function showProduct(id){const p=products.find(p=>p.id===id);document.querySelector('#dialog-content').innerHTML=`<img class="dialog-image" src="${p.image}" alt="Imagem demonstrativa"><div class="dialog-info"><p class="tag">${p.brand} · ${p.category}</p><h2>${p.name}</h2><p class="price">${money.format(p.price)}</p><p>${p.description}</p><p class="sizes">${p.sizes.map(s=>`<span>${s}</span>`).join('')}</p><button class="button primary" data-add="${p.id}">Adicionar ao carrinho</button></div>`;document.querySelector('#product-dialog').showModal()}
function checkout(){if(!cart.length)return;const lines=cart.map(i=>{const p=products.find(p=>p.id===i.id);return `• ${p.name} (${i.quantity}x) — ${money.format(p.price*i.quantity)}`});const total=cart.reduce((sum,i)=>sum+products.find(p=>p.id===i.id).price*i.quantity,0);window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(`Olá, CHUTEIRAS MBM! Quero fazer este pedido:\n\n${lines.join('\n')}\n\nTotal: ${money.format(total)}`)}`,'_blank','noopener')}
document.addEventListener('click',e=>{const id=Number(e.target.closest('[data-add]')?.dataset.add);if(id)addToCart(id);const product=Number(e.target.closest('[data-product]')?.dataset.product);if(product)showProduct(product);if(e.target.dataset.quantity)changeQuantity(Number(e.target.dataset.quantity),Number(e.target.dataset.step));if(e.target.dataset.remove){cart=cart.filter(i=>i.id!==Number(e.target.dataset.remove));renderCart()}});
[search,brandFilter,categoryFilter,sort].forEach(el=>el.addEventListener(el===search?'input':'change',renderProducts));
document.querySelectorAll('.mode-card').forEach(b=>b.addEventListener('click',()=>{categoryFilter.value=b.dataset.category;renderProducts();document.querySelector('#catalogo').scrollIntoView({behavior:'smooth'})}));
const drawer=document.querySelector('#cart-drawer'),overlay=document.querySelector('#overlay');document.querySelector('#open-cart').onclick=()=>{drawer.classList.add('open');overlay.classList.add('open');drawer.setAttribute('aria-hidden','false')};function closeCart(){drawer.classList.remove('open');overlay.classList.remove('open');drawer.setAttribute('aria-hidden','true')}document.querySelector('#close-cart').onclick=closeCart;overlay.onclick=closeCart;document.querySelector('#checkout').onclick=checkout;document.querySelector('#close-dialog').onclick=()=>document.querySelector('#product-dialog').close();document.querySelector('#whatsapp-float').href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent('Olá, CHUTEIRAS MBM! Preciso de ajuda para escolher uma chuteira.')}`;
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('nav');menu.onclick=()=>{const isOpen=nav.classList.toggle('open');menu.setAttribute('aria-expanded',isOpen)};renderProducts();renderCart();
